### ISSUE TITLE
Remove StyleSheet

### ISSUE THREAD

**Issue by clivemo** [jouni/CSSInject#7]
What's wrong with this picture?

```
public void removeStyleSheet(Resource styleSheet) {
    if(this.styleSheets == null) {
        this.styleSheets.remove(styleSheet);
    }

}
```

Brgds
Joakim

**Comment by jouni** [comment]
Should be fixed now with #9 

Would need to build a new release for this, but I’m currently very rusty with Vaadin add-ons. If there’s a demand, I can try to brush off the rustiness :)
